name: social_media_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.1
  equatable: ^2.0.5
  firebase_authentication_client:
    path: packages/authentication_client/firebase_authentication_client
  firebase_core: ^2.8.0
  firebase_user_client:
    path: packages/user_client/firebase_user_client
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  form_inputs:
    path: packages/form_inputs
  go_router: ^8.0.2
  image_picker: ^0.8.7
  intl: ^0.17.0
  secure_storage:
    path: packages/storage/secure_storage
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
